#!/usr/bin/env python3
"""Publish byte-identical generated JSON in one monitor-feed commit."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

FILES = ("health.json", "delta.json", "latest.json")
BRANCH = "monitor-feed"
BOT_NAME = "github-actions[bot]"
BOT_EMAIL = "41898282+github-actions[bot]@users.noreply.github.com"


def validate_feed(directory: Path) -> None:
    documents = {}
    for name in FILES:
        with (directory / name).open(encoding="utf-8") as stream:
            document = json.load(stream)
        if not isinstance(document, dict):
            raise ValueError(f"{name} must contain a JSON object")
        documents[name] = document
    generation = documents["health.json"].get("generated_at_jst")
    if not isinstance(generation, str) or not generation.strip():
        raise ValueError("health.json.generated_at_jst is required")
    if documents["delta.json"].get("generated_at_jst") != generation:
        raise ValueError("health.json and delta.json generations must match")
    latest = documents["latest.json"]
    if "generated_at_jst" in latest and latest["generated_at_jst"] != generation:
        raise ValueError("latest.json generation must match health.json")


def git(repository: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repository), *args],
        check=check, capture_output=True, text=True, encoding="utf-8",
    )


def publish_feed(repository: Path, source: Path) -> bool:
    """Return whether a commit was pushed; never switch the source checkout."""
    repository = repository.resolve()
    source = source.resolve()
    validate_feed(source)
    with tempfile.TemporaryDirectory(prefix="scp-jp-monitor-feed-") as temporary:
        staging = Path(temporary) / "validated"
        staging.mkdir()
        for name in FILES:
            shutil.copyfile(source / name, staging / name)
        validate_feed(staging)

        remote = git(repository, "ls-remote", "--exit-code", "--heads",
                     "origin", f"refs/heads/{BRANCH}", check=False)
        if remote.returncode == 0:
            git(repository, "fetch", "--no-tags", "origin", f"refs/heads/{BRANCH}")
            base = git(repository, "rev-parse", "FETCH_HEAD").stdout.strip()
        elif remote.returncode == 2:
            base = "HEAD"
        else:
            remote.check_returncode()

        worktree = Path(temporary) / "worktree"
        git(repository, "worktree", "add", "--detach", str(worktree), base)
        orphan_created = False
        try:
            if remote.returncode == 2:
                git(worktree, "switch", "--orphan", BRANCH)
                orphan_created = True
            git(worktree, "rm", "-r", "--ignore-unmatch", "--", ".")
            for name in FILES:
                shutil.copyfile(staging / name, worktree / name)
            validate_feed(worktree)
            # Disable platform line-ending conversion and inherited attributes.
            # Force adding the allowlist also handles a stale .gitignore.
            git(worktree, "-c", "core.autocrlf=false", "-c", "core.attributesFile=",
                "add", "--force", "--", *FILES)
            tracked = git(worktree, "ls-files").stdout.splitlines()
            if set(tracked) != set(FILES):
                raise ValueError("Feed commit must contain only the three public JSON files")
            for name in FILES:
                blob = subprocess.run(
                    ["git", "-C", str(worktree), "show", f":{name}"],
                    check=True, capture_output=True,
                ).stdout
                if blob != (staging / name).read_bytes():
                    raise ValueError(f"Git would change the generated bytes of {name}")
            difference = git(worktree, "diff", "--cached", "--quiet", check=False)
            if difference.returncode == 0:
                print("Raw monitor feed is unchanged; no commit needed.")
                return False
            if difference.returncode != 1:
                difference.check_returncode()
            git(worktree, "-c", f"user.name={BOT_NAME}", "-c", f"user.email={BOT_EMAIL}",
                "commit", "-m", "chore: publish SCP-JP monitor feed [skip ci]")
            # No force: a concurrent writer must not replace a newer feed.
            git(worktree, "push", "origin", f"HEAD:refs/heads/{BRANCH}")
            print("Published all three JSON files to origin monitor-feed.")
            return True
        finally:
            git(repository, "worktree", "remove", "--force", str(worktree))
            if orphan_created:
                # This invocation owns the temporary local orphan branch. A
                # failed first push must not prevent a retry in this checkout.
                git(repository, "branch", "-D", BRANCH, check=False)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--public-dir", type=Path, required=True)
    args = parser.parse_args()
    try:
        publish_feed(Path.cwd(), args.public_dir)
    except subprocess.CalledProcessError as error:
        # Git's stderr supplies the operational cause (e.g. push permissions).
        parser.exit(1, f"Raw feed publication failed: {error.stderr or error}\n")
    except (OSError, ValueError) as error:
        parser.exit(1, f"Raw feed publication failed: {error}\n")


if __name__ == "__main__":
    main()
